listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_anonymous true
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

max_inflight_messages 100
max_queued_messages 1000
message_size_limit 0
queue_qos0_messages true

connection_messages true
sys_interval 60
